logging:
    level:
        com:
            khmersolution:
                moduler: DEBUG
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor:
                        sql: trace
    pattern:
        console: '%clr(%d{HH:mm:ss}){magenta} %-5level - %clr(%msg%n){cyan}'
        file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
security:
    oauth2:
        resource:
            filter-order: 3
        resourceId: oauth2-jwt-resource
        realm: trusted-app
        client-id: trusted-app
        client-secret: secret
        grant-type: password #client_credentials, password, refresh_token
        authorities: TRUSTED_CLIENT
        url: http://localhost:9999/oauth/token
server:
    port: ${PORT:9999}
    contextPath: /
spring:
    data:
        rest:
            basePath: /rest/api
#    datasource:
#        driverClassName: org.postgresql.Driver
#        maxActive: 5
#        password: postgres
#        url: jdbc:postgresql://localhost:5432/postgres
#        username: postgres
    datasource:
        driver-class-name: org.h2.Driver
        maxActive: 5
        password:
        url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQLDialect
                dialect: org.hibernate.dialect.H2Dialect
                formatSql: false
        showSql: false
###### Custom Swagger Properties
swagger:
    apiInfo:
        contactEmail: ravuthz@gmail.com
        contactName: ravuthz@gmail.com
        contactUrl: http://github.com/ravuthz/user-management-api
        description: Users Management REST API with Spring Boot + Spring Data JPA + Spring Data REST + Spring Security + Spring Security JWT + Spring Security OAUTH 2.
        license: Apache 2.0
        licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
        termOfServiceUrl: http://swagger.io/terms/
        title: User Management API
        version: 1.0.0
    defaultKey:
        page: page
        size: size
        sort: sort
    defaultValue:
        page: 0
        size: 20
        sort: id,desc
